# This is a basic workflow to help you get started with Actions

name: docker-compose CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run docker-compose
        run: docker-compose up -d
        
      - name: Check containers
        run: |
          docker ps | grep -E '.*semarchy-docker-compose_web.*Up'
          docker ps | grep -E '.*semarchy-docker-compose_web.*Up'
          docker ps | grep -E '.*pgadmin4.*Up'
          
      - name: Build and push semarchy image
        uses: docker/build-push-action@v1.1.1
        with:
          # Username used to log in to a Docker registry. If not set then no login will occur
          username: galbirk
          # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
          password: ${{ secrets.DOCKER_HUB_PASS }}
          # Docker repository to tag the image with
          repository: galbirk/semarchy
          # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
          tags: postgres
          # Path to the build context
          path: ./web
          # Always attempt to pull a newer version of the image
          always_pull: true
          push: true
  
      - name: Build and push postgres image
        uses: docker/build-push-action@v1.1.1
        with:
          # Username used to log in to a Docker registry. If not set then no login will occur
          username: galbirk
          # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
          password: ${{ secrets.DOCKER_HUB_PASS }}
          # Docker repository to tag the image with
          repository: galbirk/postgres
          # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
          tags: 9.6-semarchy
          # Path to the build context
          path: ./db
          # Always attempt to pull a newer version of the image
          always_pull: true
          push: true
