# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
    - master
  tags:
    include:
    - '*'

resources:
- repo: self

variables:
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    tag: 'latest'
  ${{ if ne(variables['Build.SourceBranchName'], 'master') }}:
    tag: ${{ variables['Build.SourceBranchName'] }}
  imageName: 'pernodricard/semarchy'
  dockerHubConnectionName: 'Docker Hub'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build image
      inputs:
        command: build
        repository: $(imageName)
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Push image
      inputs:
        command: push
        repository: $(imageName)
        containerRegistry: $(dockerHubConnectionName)
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)